"""add detail column on Class table

Revision ID: 02f17d47b7ed
Revises: 9caefafb7ce9
Create Date: 2025-08-19 18:19:46.233731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f17d47b7ed'
down_revision: Union[str, None] = '9caefafb7ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('detail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'detail')
    # ### end Alembic commands ###
