"""change Class.name to unique

Revision ID: 4775e06e1290
Revises: 79076eec6dff
Create Date: 2025-08-19 23:44:59.601825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4775e06e1290'
down_revision: Union[str, None] = '79076eec6dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='unique')
    # ### end Alembic commands ###
