"""add relation cascade on enrollments and classes table

Revision ID: 47899f69f39e
Revises: 56bb5384bf18
Create Date: 2025-08-20 17:12:02.320128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47899f69f39e'
down_revision: Union[str, None] = '56bb5384bf18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('enrollments_user_id_fkey'), 'enrollments', type_='foreignkey')
    op.drop_constraint(op.f('enrollments_class_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollments', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_class_id_fkey'), 'enrollments', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(op.f('enrollments_user_id_fkey'), 'enrollments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
