"""add enrolled_at column on enrollments table

Revision ID: 9caefafb7ce9
Revises: 253c4309214e
Create Date: 2025-08-19 12:10:45.962815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caefafb7ce9'
down_revision: Union[str, None] = '253c4309214e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'enrolled_at')
    # ### end Alembic commands ###
